#!/bin/bash

monitor_count=

wallpapers=$(
    xrandr | grep ' connected' | while read monitor ; do
        ~/.dotfiles/scripts/bz-fetch-wallpaper &
    done
    wait
)

feh --no-fehbg --bg-scale $wallpapers